server:
  port: 10010
spring:
  application:
    name: chess-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
#ribbon:
#  ConnectTimeout: 250 # 连接超时时间(ms)
#  ReadTimeout: 2000 # 通信超时时间(ms)
#  OkToRetryOnAllOperations: true # 是否对所有操作重试
#  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
#  MaxAutoRetries: 0 # 同一实例的重试次数
#hystrix:
#  command: 
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms