var path = "http://120.78.94.125:8081";
var index_url = "/Client/index.html";
var getUser_url = path + "/user/getUser";
var loginUrl = path+'/user/login';
var register_url = path + '/user/register';
var ws = "ws://120.78.94.125:8081/websocket/1";
var chese_url = "/Client/cheses.html";
var getRankInfo_url = path = "/rank/getRank/";
var getUserInfo_url = path + "/user/getUserInfo/";
var updateFriendLaunch_url = path + "/friendLaunchMessage/updateFriendLaunch/";